### ISSUE TITLE
CentOS 8 and Fedora 36 images:  setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

### ISSUE THREAD

**Issue by bording** [GitTools/build-images#22]
While working on https://github.com/libgit2/libgit2sharp/pull/2028, I came across a problem with the `centos.stream.8` and `fedora.36` images.

During the build, I was getting the following warning:
```
/usr/bin/sh : warning : setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```
And then I ended up getting a build failure because of malformed versioning attributes.

It looks like this is the reason MSBuild is trying to set the locale and failing: https://github.com/dotnet/msbuild/issues/4194

Searching around a bit more, I came across an issue that said that you could fix the problem by installing the `glibc-langpack-en` package and pointed to https://bugzilla.redhat.com/show_bug.cgi?id=1677927#c7 as the source of that info.

I tested that on the two images locally, and that did seem to make everything work. Any chance of getting that added to the base `centos.stream.8` and `fedora.36` images here? Those were the only two that seemed to be impacted.

**Comment by arturcic** [comment]
Thanl you @bording for the details, I will check that and let you know when it's done.

**Comment by arturcic** [comment]
@bording can you give it a try now with the new images?

**Comment by bording** [comment]
Looks like they are working now. Thanks!
